# Generated by Django 3.2.14 on 2022-08-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_sending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='massage',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='massages',
                to='server_sending.massage',
            ),
        ),
    ]
