# Generated by Django 3.2.14 on 2022-08-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_sending', '0002_alter_sending_massage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sending',
            name='massage',
        ),
        migrations.AddField(
            model_name='sending',
            name='massage_txt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sending',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='sending',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
