# Generated by Django 3.2.14 on 2022-08-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_sending', '0003_auto_20220809_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='massage_txt',
        ),
    ]
